# USAID GHSC-PSM Health Commodity Delivery Dataset

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/USAID_GHSC-PSM_Health_Commodity_Delivery_Dataset.csv')

<ipython-input-2-6b7a9a1a3dbf>:1: DtypeWarning: Columns (31,74,75,76,87,88,89,91,92) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/content/USAID_GHSC-PSM_Health_Commodity_Delivery_Dataset.csv')

In [ ]:
data

,ROPOLine,Task Order,Condom Adjusted Task Order,Country,RO Number,PO DO IO Number,Order Number,Prime Line Number,Status Name,TLP Indicator,...,RO Validation,Sourcing and Planning,USAID Approval,Process PO/DO,Manufacture,Pick Up,Deliver,Quality Assurance,Reason Code,Reason Code Duration
0,RO10026301PO100041611,TO1,TO1,Haiti,RO10026301,PO10004161,PO10004161,1,Shipment Delivered,DCP,...,NaN,NaN,0.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN
1,RO10043181PO100076996,TO1,TO1,Zambia,RO10043181,PO10007699,PO10007699,6,Shipment Delivered,DCP,...,NaN,NaN,3.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN
2,RO10022196PO100016001,TO1,TO1,Mozambique,RO10022196,PO10001600,PO10001600,1,Shipment Delivered,DCP,...,NaN,NaN,13.0,209.0,NaN,NaN,NaN,NaN,NaN,NaN
3,RO10060249PO100087742,TO1,TO1,Zambia,RO10060249,PO10008774,PO10008774,2,Shipment Delivered,DCP,...,NaN,NaN,0.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN
4,RO10036286PO100045152,TO1,TO1,Mozambique,RO10036286,PO10004515,PO10004515,2,Shipment Delivered,DCP,...,NaN,NaN,0.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43391,RO10111215PO100179901,TO2,TO2,Liberia,RO10111215,PO10017990,PO10017990,1,Shipment Delivered,GSC,...,8.0,161.0,2.0,5.0,62.0,23.0,54.0,10.0,AD012,-17.0
43392,RO10063176PO100089941,TO2,TO2,Burkina Faso,RO10063176,PO10008994,PO10008994,1,Shipment Delivered,GSC,...,NaN,NaN,5.0,141.0,23.0,6.0,54.0,20.0,AD012,-56.0
43393,RO10063115PO100092764,TO2,TO2,Malawi,RO10063115,PO10009276,PO10009276,4,Shipment Delivered,GSC,...,15.0,44.0,0.0,39.0,266.0,28.0,52.0,34.0,AD012,-21.0
43394,RO10165130PO100250231,TO2,TO2,Kenya,RO10165130,PO10025023,PO10025023,1,Shipment Delivered,GSC,...,62.0,69.0,1.0,5.0,137.0,32.0,68.0,19.0,AD012,-38.0
43395,RO10184181PO100272832,TO2,TO2,Congo DRC,RO10184181,PO10027283,PO10027283,2,Shipment Delivered,GSC,...,27.0,55.0,0.0,21.0,21.0,45.0,124.0,31.0,AD012,-20.0

In [ ]:
list(data.columns)

['ROPOLine',
 'Task Order',
 'Condom Adjusted Task Order',
 'Country',
 'RO Number',
 'PO DO IO Number',
 'Order Number',
 'Prime Line Number',
 'Status Name',
 'TLP Indicator',
 'Order Type',
 'Fulfillment Method',
 'Transportation Mode',
 'Item Tracer Category',
 'Product Category',
 'Product ID',
 'Product_Name',
 'UOM',
 'Base Unit',
 'Base Unit Multiplier',
 'Framework Contract',
 'D365 Health Element',
 'D365 Funding Source',
 'D365 Funding Source Detail',
 'Fiscal_Year_Funding',
 'Estimated Lead Time in Days',
 'Vendor Incoterm',
 'Destination Incoterm',
 'Illustrative Price',
 'Ordered Quantity',
 'Shipped Quantity',
 'OTD OTIF Exclusion Flag',
 'In Full (IFD)',
 'On Time (OTD)',
 'Between -14 and 14',
 'Between -30 and 30',
 'OTIF Categories',
 'OTIF Between -14 and 14',
 'OTIF Between -30 and 30',
 'Average Days Late Binned',
 'Average Days Late',
 'Number of Shipments',
 'Delivery Progress',
 'Line Delivery Status',
 'Agreed Delivery Date',
 'Agreed Delivery Date Year',
 'Agreed Delivery Date Year Month',
 'Agreed Delivery Date Fiscal Year',
 'Agreed Delivery Date Fiscal Quarter Year',
 'Revised Agreed Delivery Date',
 'Revised Agreed Delivery Date Year',
 'Revised Agreed Delivery Date Year Month',
 'Revised Agreed Delivery Date Fiscal Year',
 'Revised Agreed Delivery Date Fiscal Quarter Year',
 'Order Entry Date',
 'Order Entry Date Year',
 'Order Entry Date Year Month',
 'Order Entry Date Fiscal Year',
 'Order Entry Date Fiscal Quarter Year',
 'Requested Delivery Date',
 'Requested Delivery Date Year',
 'Requested Delivery Date Year Month',
 'Requested Delivery Date Fiscal Year',
 'Requested Delivery Date Fiscal Quarter Year',
 'Estimated Delivery Date',
 'Estimated Delivery Date Year',
 'Estimated Delivery Date Year Month',
 'Estimated Delivery Date Fiscal Year',
 'Estimated Delivery Date Fiscal Quarter Year',
 'Latest Actual Delivery Date',
 'Latest Actual Delivery Date Year',
 'Latest Actual Delivery Date Year Month',
 'Latest Actual Delivery Date Fiscal Year',
 'Latest Actual Delivery Date Fiscal Quarter Year',
 'RO Clarified Date',
 'RO Sent Plan Fulfillment Date',
 'RO Sent Sourcing RFX Event Date',
 'Initial PSM Source Approval Date',
 'Recipient Approval Date',
 'USAID Approval Date',
 'PO Released For Fulfillment Date',
 'PO Released For Fulfillment Date Year',
 'PO Released For Fulfillment Date Year Month',
 'PO Released For Fulfillment Date Fiscal Year',
 'PO Released For Fulfillment Date Fiscal Quarter Year',
 'Committed Goods Available Date',
 'Actual Goods Available Date',
 'Actual Cargo Ready Date',
 'QA Complete Date',
 'Max Pick Up Date',
 'Max Ship Date',
 'Max Departure Date',
 'Max Arrival Date',
 'Order Cycle Time',
 'RO Validation',
 'Sourcing and Planning',
 'USAID Approval',
 'Process PO/DO',
 'Manufacture',
 'Pick Up',
 'Deliver',
 'Quality Assurance',
 'Reason Code',
 'Reason Code Duration']

In [ ]:
columns = ["Framework Contract", "PO DO IO Number", "Product ID"]
data[columns]

      Framework Contract PO DO IO Number    Product ID
0          Non-Framework      PO10004161  101208XUZ0B1
1          Non-Framework      PO10007699  101208XUZ0B1
2          Non-Framework      PO10001600  101208XUZ0B1
3          Non-Framework      PO10008774  101203XUZ0B9
4          Non-Framework      PO10004515  101158XUZ01S
...                  ...             ...           ...
43391          Framework      PO10017990  100076AAA08Z
43392      Non-Framework      PO10008994  100774XLL01S
43393          Framework      PO10009276  100062XXC08D
43394          Framework      PO10025023  104290LLX01S
43395          Framework      PO10027283  100076AAK08X

[43396 rows x 3 columns]

In [ ]:
data['Framework Contract'].unique()

array(['Non-Framework', 'Framework', nan], dtype=object)

In [ ]:
data['PO DO IO Number'].unique()

array(['PO10004161', 'PO10007699', 'PO10001600', ..., 'PO10017990',
       'PO10008994', 'PO10025023'], dtype=object)

In [ ]:
data['Product ID'].unique()

array(['101208XUZ0B1', '101203XUZ0B9', '101158XUZ01S', ...,
       '101874XLN01S', '104310LLX01S', '100055XLK01S'], dtype=object)

In [ ]:
# Time-Based Columns: Agreed Delivery Date, Requested Delivery Date, Estimated Delivery Date

# Quantitative Data: Ordered Quantity, Shipped Quantity, Illustrative Price, Average Days Late

# Categorical Data: Product Category, Country, Vendor Incoterm, Reason Code, Transportation Mode
data['Agreed Delivery Date'].dtypes

dtype('O')

In [ ]:
# import pandas as pd

# # Convert the column to datetime
# data['Agreed Delivery Date'] = pd.to_datetime(data['Agreed Delivery Date'])

# # Format the date as desired
# data['Agreed Delivery Date'] = pd.to_datetime(data['Agreed Delivery Date'], format='%A, %B %d, %Y')

In [ ]:
data['Agreed Delivery Date']

0           Friday, February 17, 2017
1               Monday, July 16, 2018
2                 Sunday, May 7, 2017
3           Monday, December 16, 2019
4        Wednesday, December 27, 2017
                     ...
43391          Thursday, July 8, 2021
43392           Monday, June 24, 2019
43393        Friday, December 6, 2019
43394     Thursday, December 21, 2023
43395          Monday, August 5, 2024
Name: Agreed Delivery Date, Length: 43396, dtype: object

In [ ]:
data['Agreed Delivery Date Year Month']

0        2017-02
1        2018-07
2        2017-05
3        2019-12
4        2017-12
          ...
43391    2021-07
43392    2019-06
43393    2019-12
43394    2023-12
43395    2024-08
Name: Agreed Delivery Date Year Month, Length: 43396, dtype: object

In [ ]:
data['Agreed Delivery Date']

0           Friday, February 17, 2017
1               Monday, July 16, 2018
2                 Sunday, May 7, 2017
3           Monday, December 16, 2019
4        Wednesday, December 27, 2017
                     ...
43391          Thursday, July 8, 2021
43392           Monday, June 24, 2019
43393        Friday, December 6, 2019
43394     Thursday, December 21, 2023
43395          Monday, August 5, 2024
Name: Agreed Delivery Date, Length: 43396, dtype: object

In [ ]:
required_fields = [
    "Order Number",
    "On Time (OTD)",
    "Illustrative Price",
    "Shipped Quantity",
    "Delivery Progress",
    "Transportation Mode",
    "Agreed Delivery Date",
    'Latest Actual Delivery Date'
]


data[required_fields]

,Order Number,On Time (OTD),Illustrative Price,Shipped Quantity,Delivery Progress,Transportation Mode,Agreed Delivery Date,Latest Actual Delivery Date
0,PO10004161,Y,348.01,540,2,Land,"Friday, February 17, 2017","Wednesday, February 22, 2017"
1,PO10007699,Y,348.01,191,2,Land,"Monday, July 16, 2018","Tuesday, July 17, 2018"
2,PO10001600,Y,348.01,730,2,Land,"Sunday, May 7, 2017","Tuesday, June 6, 2017"
3,PO10008774,Y,137.00,210,2,Land,"Monday, December 16, 2019","Friday, December 20, 2019"
4,PO10004515,Y,150.00,48,2,Land,"Wednesday, December 27, 2017","Thursday, November 23, 2017"
...,...,...,...,...,...,...,...,...
43391,PO10017990,Y,19.12,6194,2,Sea,"Thursday, July 8, 2021","Monday, June 21, 2021"
43392,PO10008994,Y,1.86,7149,2,Sea,"Monday, June 24, 2019","Monday, April 29, 2019"
43393,PO10009276,Y,6.54,26666,2,Sea,"Friday, December 6, 2019","Friday, November 15, 2019"
43394,PO10025023,Y,2.79,325000,2,Sea,"Thursday, December 21, 2023","Monday, November 13, 2023"
43395,PO10027283,Y,12.49,4498,2,Sea,"Monday, August 5, 2024","Tuesday, July 16, 2024"

### Delivery and logistics insights

In [ ]:
delivery_timelines = [
    "Agreed Delivery Date",
    "Estimated Delivery Date",
    "Latest Actual Delivery Date",
    "Average Days Late",
    "Number of Shipments"
]

data[delivery_timelines]

,Agreed Delivery Date,Estimated Delivery Date,Latest Actual Delivery Date,Average Days Late,Number of Shipments
0,"Friday, February 17, 2017","Wednesday, February 15, 2017","Wednesday, February 22, 2017",5.0,1
1,"Monday, July 16, 2018","Monday, July 16, 2018","Tuesday, July 17, 2018",1.0,1
2,"Sunday, May 7, 2017","Tuesday, June 6, 2017","Tuesday, June 6, 2017",0.0,1
3,"Monday, December 16, 2019","Monday, December 16, 2019","Friday, December 20, 2019",4.0,1
4,"Wednesday, December 27, 2017","Wednesday, December 27, 2017","Thursday, November 23, 2017",-7.0,1
...,...,...,...,...,...
43391,"Thursday, July 8, 2021","Friday, June 18, 2021","Monday, June 21, 2021",0.0,1
43392,"Monday, June 24, 2019","Sunday, April 28, 2019","Monday, April 29, 2019",0.0,1
43393,"Friday, December 6, 2019","Friday, November 15, 2019","Friday, November 15, 2019",0.0,1
43394,"Thursday, December 21, 2023","Sunday, November 12, 2023","Monday, November 13, 2023",0.0,1
43395,"Monday, August 5, 2024","Friday, July 19, 2024","Tuesday, July 16, 2024",0.0,1

In [ ]:
cost_and_logistics = [
    "Transportation Mode",
    "Vendor Incoterm",
    "Destination Incoterm",
    "Illustrative Price"
]

data[cost_and_logistics]

,Transportation Mode,Vendor Incoterm,Destination Incoterm,Illustrative Price
0,Land,DDP,DDP,348.01
1,Land,DDP,DDP,348.01
2,Land,DDP,NaN,348.01
3,Land,DDP,DDP,137.00
4,Land,DDP,DDP,150.00
...,...,...,...,...
43391,Sea,FCA,DDP,19.12
43392,Sea,FCA,DAP,1.86
43393,Sea,FCA,CIF,6.54
43394,Sea,FCA,DAP,2.79
43395,Sea,FCA,DAP,12.49

In [ ]:
performance_metrics = [
    "On Time (OTD)",
    "In Full (IFD)",
    "OTIF Categories"
]

data[performance_metrics]

      On Time (OTD) In Full (IFD)  OTIF Categories
0                 Y             Y  On Time In Full
1                 Y             Y  On Time In Full
2                 Y             Y  On Time In Full
3                 Y             Y  On Time In Full
4                 Y             Y  On Time In Full
...             ...           ...              ...
43391             Y             Y  On Time In Full
43392             Y             Y  On Time In Full
43393             Y             Y  On Time In Full
43394             Y             Y  On Time In Full
43395             Y             Y  On Time In Full

[43396 rows x 3 columns]

In [ ]:
identifiers = [
    "Country",
    "Order Number",
    "Product_Name",
    "Product Category"
]

data[identifiers]

,Country,Order Number,Product_Name,Product Category
0,Haiti,PO10004161,"Sysmex Stromatolyser-WH, 500 mL, 3 Each",Laboratory Reagents
1,Zambia,PO10007699,"Sysmex Stromatolyser-WH, 500 mL, 3 Each",Laboratory Reagents
2,Mozambique,PO10001600,"Sysmex Stromatolyser-WH, 500 mL, 3 Each",Laboratory Reagents
3,Zambia,PO10008774,"ABX Minotrol 16 Twin-Pack, High, 2 x 2.5 mL, 1...",Laboratory Reagents
4,Mozambique,PO10004515,"m2000 Halogen Lamp, Replacement [09K33-01], 1 ...",Laboratory Equipment
...,...,...,...,...
43391,Liberia,PO10017990,"Artemether/Lumefantrine 20/120 mg Tablet, 30 x...",Malaria Pharmaceuticals
43392,Burkina Faso,PO10008994,Long Lasting Insecticide Treated Net (LLIN) 18...,Long Lasting Insecticide Treated Nets (LLINs)
43393,Malawi,PO10009276,Malaria Rapid Diagnostic Test (RDT) HRP2 (Pf) ...,Malaria Rapid Diagnostic Test (RDTs)
43394,Kenya,PO10025023,(Campaign Individual) LLIN 190x180x170 cm (LxW...,Long Lasting Insecticide Treated Nets (LLINs)
43395,Congo DRC,PO10027283,Artemether/Lumefantrine 20/120 mg Dispersible ...,Malaria Pharmaceuticals

In [ ]:
fields = [
    # 1. Order Information
    "Order Number",
    "Country",
    "Product_Name",
    "Product Category",

    # 2. Shipping and Logistics Setup
    "Vendor Incoterm",
    "Destination Incoterm",
    "Transportation Mode",
    "Illustrative Price",

    # 3. Delivery Timeline and Progress
    "Agreed Delivery Date",
    "Estimated Delivery Date",
    "Latest Actual Delivery Date",
    "Number of Shipments",
    "Average Days Late",

    # 4. Delivery Performance Evaluation
    "On Time (OTD)",
    "In Full (IFD)",
    "OTIF Categories"
]

data[fields]

,Order Number,Country,Product_Name,Product Category,Vendor Incoterm,Destination Incoterm,Transportation Mode,Illustrative Price,Agreed Delivery Date,Estimated Delivery Date,Latest Actual Delivery Date,Number of Shipments,Average Days Late,On Time (OTD),In Full (IFD),OTIF Categories
0,PO10004161,Haiti,"Sysmex Stromatolyser-WH, 500 mL, 3 Each",Laboratory Reagents,DDP,DDP,Land,348.01,"Friday, February 17, 2017","Wednesday, February 15, 2017","Wednesday, February 22, 2017",1,5.0,Y,Y,On Time In Full
1,PO10007699,Zambia,"Sysmex Stromatolyser-WH, 500 mL, 3 Each",Laboratory Reagents,DDP,DDP,Land,348.01,"Monday, July 16, 2018","Monday, July 16, 2018","Tuesday, July 17, 2018",1,1.0,Y,Y,On Time In Full
2,PO10001600,Mozambique,"Sysmex Stromatolyser-WH, 500 mL, 3 Each",Laboratory Reagents,DDP,NaN,Land,348.01,"Sunday, May 7, 2017","Tuesday, June 6, 2017","Tuesday, June 6, 2017",1,0.0,Y,Y,On Time In Full
3,PO10008774,Zambia,"ABX Minotrol 16 Twin-Pack, High, 2 x 2.5 mL, 1...",Laboratory Reagents,DDP,DDP,Land,137.00,"Monday, December 16, 2019","Monday, December 16, 2019","Friday, December 20, 2019",1,4.0,Y,Y,On Time In Full
4,PO10004515,Mozambique,"m2000 Halogen Lamp, Replacement [09K33-01], 1 ...",Laboratory Equipment,DDP,DDP,Land,150.00,"Wednesday, December 27, 2017","Wednesday, December 27, 2017","Thursday, November 23, 2017",1,-7.0,Y,Y,On Time In Full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43391,PO10017990,Liberia,"Artemether/Lumefantrine 20/120 mg Tablet, 30 x...",Malaria Pharmaceuticals,FCA,DDP,Sea,19.12,"Thursday, July 8, 2021","Friday, June 18, 2021","Monday, June 21, 2021",1,0.0,Y,Y,On Time In Full
43392,PO10008994,Burkina Faso,Long Lasting Insecticide Treated Net (LLIN) 18...,Long Lasting Insecticide Treated Nets (LLINs),FCA,DAP,Sea,1.86,"Monday, June 24, 2019","Sunday, April 28, 2019","Monday, April 29, 2019",1,0.0,Y,Y,On Time In Full
43393,PO10009276,Malawi,Malaria Rapid Diagnostic Test (RDT) HRP2 (Pf) ...,Malaria Rapid Diagnostic Test (RDTs),FCA,CIF,Sea,6.54,"Friday, December 6, 2019","Friday, November 15, 2019","Friday, November 15, 2019",1,0.0,Y,Y,On Time In Full
43394,PO10025023,Kenya,(Campaign Individual) LLIN 190x180x170 cm (LxW...,Long Lasting Insecticide Treated Nets (LLINs),FCA,DAP,Sea,2.79,"Thursday, December 21, 2023","Sunday, November 12, 2023","Monday, November 13, 2023",1,0.0,Y,Y,On Time In Full
43395,PO10027283,Congo DRC,Artemether/Lumefantrine 20/120 mg Dispersible ...,Malaria Pharmaceuticals,FCA,DAP,Sea,12.49,"Monday, August 5, 2024","Friday, July 19, 2024","Tuesday, July 16, 2024",1,0.0,Y,Y,On Time In Full

In [ ]:
data[f'Number of Shipments'].unique()

array([ 1,  2,  5,  4,  3,  8,  9,  6, 13, 10,  7, 19, 12, 15, 14, 22, 25,
       16, 11, 32, 23, 17, 18])

In [ ]:
# Plot 1: Bar chart, Geographical Map or Heatmap
"""Average Days Late(5.0) and Country (Haiti)"""

# Plot 2: Line Chart
"""Agreed Delivery Date Year Month(February 2017) and OTD Percentage(0-Late, 1-On-time)"""

# Plot 3: Line Chart
"""Agreed Delivery Date Year Month and OTD Percentage"""


"""
TABLE Option A: Delivery Performance by Country
Fields: Country, Number of Shipments, Average Days Late, On Time (OTD) percentage
Sorting: By Average Days Late (descending)
Why it works: Provides clear country-level performance at a glance, allows for quick identification of problematic regions

BAR CHART Option C: On-Time Delivery Performance by Transportation Mode
X-axis: Transportation Mode
Y-axis: Percentage of On-Time Deliveries (OTD)
Color: Product Category
Why it works: Clearly shows which transportation methods are most reliable

TREND CHART Option A: OTD Percentage Over Time
X-axis: Agreed Delivery Date Year Month
Y-axis: OTD Percentage
Color: Transportation Mode
Why it works: Shows performance trends over time, allows identification of seasonal patterns or improving/deteriorating performance

Heatmap: Worst Performing Countries by Transportation Mode
Rows: Countries (filtered by Top N Average Days Late)
Columns: Transportation Mode
Color: Average Days Late (darker = worse performance)
Size: Number of Shipments (larger = more volume)
This visualization instantly shows which country-transportation mode combinations have the worst performance
"""

'\nTABLE Option A: Delivery Performance by Country\nFields: Country, Number of Shipments, Average Days Late, On Time (OTD) percentage\nSorting: By Average Days Late (descending)\nWhy it works: Provides clear country-level performance at a glance, allows for quick identification of problematic regions\n\nBAR CHART Option C: On-Time Delivery Performance by Transportation Mode\nX-axis: Transportation Mode\nY-axis: Percentage of On-Time Deliveries (OTD)\nColor: Product Category\nWhy it works: Clearly shows which transportation methods are most reliable\n\nTREND CHART Option A: OTD Percentage Over Time\nX-axis: Agreed Delivery Date Year Month\nY-axis: OTD Percentage\nColor: Transportation Mode\nWhy it works: Shows performance trends over time, allows identification of seasonal patterns or improving/deteriorating performance\n\nHeatmap: Worst Performing Countries by Transportation Mode\nRows: Countries (filtered by Top N Average Days Late)\nColumns: Transportation Mode\nColor: Average Days Late (darker = worse performance)\nSize: Number of Shipments (larger = more volume)\nThis visualization instantly shows which country-transportation mode combinations have the worst performance\n'

In [ ]:
essential_columns = [
    'Country',
    'Transportation Mode',
    'Product Category',
    'Agreed Delivery Date Year Month',
    'On Time (OTD)',
    'Average Days Late',
    'Number of Shipments'
]

In [ ]:
logistics_data = data[essential_columns].copy()

In [ ]:
logistics_data

,Country,Transportation Mode,Product Category,Agreed Delivery Date Year Month,On Time (OTD),Average Days Late,Number of Shipments
0,Haiti,Land,Laboratory Reagents,2017-02,Y,5.0,1
1,Zambia,Land,Laboratory Reagents,2018-07,Y,1.0,1
2,Mozambique,Land,Laboratory Reagents,2017-05,Y,0.0,1
3,Zambia,Land,Laboratory Reagents,2019-12,Y,4.0,1
4,Mozambique,Land,Laboratory Equipment,2017-12,Y,-7.0,1
...,...,...,...,...,...,...,...
43391,Liberia,Sea,Malaria Pharmaceuticals,2021-07,Y,0.0,1
43392,Burkina Faso,Sea,Long Lasting Insecticide Treated Nets (LLINs),2019-06,Y,0.0,1
43393,Malawi,Sea,Malaria Rapid Diagnostic Test (RDTs),2019-12,Y,0.0,1
43394,Kenya,Sea,Long Lasting Insecticide Treated Nets (LLINs),2023-12,Y,0.0,1
43395,Congo DRC,Sea,Malaria Pharmaceuticals,2024-08,Y,0.0,1

In [ ]:
logistics_data.dtypes

Country                             object
Transportation Mode                 object
Product Category                    object
Agreed Delivery Date Year Month     object
On Time (OTD)                       object
Average Days Late                  float64
Number of Shipments                  int64
dtype: object

In [ ]:
logistics_data["Agreed Delivery Date Year Month"] = pd.to_datetime(logistics_data["Agreed Delivery Date Year Month"], format="%Y-%m")

In [ ]:
logistics_data["On Time (OTD)"] = logistics_data["On Time (OTD)"].replace({'Y': 1, 'N': 0})
logistics_data["On Time (OTD)"] = logistics_data["On Time (OTD)"].astype(float)
logistics_data.dtypes

<ipython-input-27-d7b4e1377a9d>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  logistics_data["On Time (OTD)"] = logistics_data["On Time (OTD)"].replace({'Y': 1, 'N': 0})

Country                                    object
Transportation Mode                        object
Product Category                           object
Agreed Delivery Date Year Month    datetime64[ns]
On Time (OTD)                             float64
Average Days Late                         float64
Number of Shipments                         int64
dtype: object

In [ ]:
logistics_data = logistics_data.dropna(subset=["Agreed Delivery Date Year Month"])

In [ ]:
logistics_data = logistics_data[logistics_data["Agreed Delivery Date Year Month"].dt.year <= 2025]

In [ ]:
logistics_data

,Country,Transportation Mode,Product Category,Agreed Delivery Date Year Month,On Time (OTD),Average Days Late,Number of Shipments
0,Haiti,Land,Laboratory Reagents,2017-02-01,1.0,5.0,1
1,Zambia,Land,Laboratory Reagents,2018-07-01,1.0,1.0,1
2,Mozambique,Land,Laboratory Reagents,2017-05-01,1.0,0.0,1
3,Zambia,Land,Laboratory Reagents,2019-12-01,1.0,4.0,1
4,Mozambique,Land,Laboratory Equipment,2017-12-01,1.0,-7.0,1
...,...,...,...,...,...,...,...
43391,Liberia,Sea,Malaria Pharmaceuticals,2021-07-01,1.0,0.0,1
43392,Burkina Faso,Sea,Long Lasting Insecticide Treated Nets (LLINs),2019-06-01,1.0,0.0,1
43393,Malawi,Sea,Malaria Rapid Diagnostic Test (RDTs),2019-12-01,1.0,0.0,1
43394,Kenya,Sea,Long Lasting Insecticide Treated Nets (LLINs),2023-12-01,1.0,0.0,1
43395,Congo DRC,Sea,Malaria Pharmaceuticals,2024-08-01,1.0,0.0,1

In [ ]:
logistics_data.isnull().sum()

Country                            0
Transportation Mode                0
Product Category                   0
Agreed Delivery Date Year Month    0
On Time (OTD)                      1
Average Days Late                  1
Number of Shipments                0
dtype: int64

In [ ]:
logistics_data.dropna(inplace=True)

In [ ]:
logistics_data.isnull().sum()

Country                            0
Transportation Mode                0
Product Category                   0
Agreed Delivery Date Year Month    0
On Time (OTD)                      0
Average Days Late                  0
Number of Shipments                0
dtype: int64

In [ ]:
logistics_data

,Country,Transportation Mode,Product Category,Agreed Delivery Date Year Month,On Time (OTD),Average Days Late,Number of Shipments
0,Haiti,Land,Laboratory Reagents,2017-02-01,1.0,5.0,1
1,Zambia,Land,Laboratory Reagents,2018-07-01,1.0,1.0,1
2,Mozambique,Land,Laboratory Reagents,2017-05-01,1.0,0.0,1
3,Zambia,Land,Laboratory Reagents,2019-12-01,1.0,4.0,1
4,Mozambique,Land,Laboratory Equipment,2017-12-01,1.0,-7.0,1
...,...,...,...,...,...,...,...
43391,Liberia,Sea,Malaria Pharmaceuticals,2021-07-01,1.0,0.0,1
43392,Burkina Faso,Sea,Long Lasting Insecticide Treated Nets (LLINs),2019-06-01,1.0,0.0,1
43393,Malawi,Sea,Malaria Rapid Diagnostic Test (RDTs),2019-12-01,1.0,0.0,1
43394,Kenya,Sea,Long Lasting Insecticide Treated Nets (LLINs),2023-12-01,1.0,0.0,1
43395,Congo DRC,Sea,Malaria Pharmaceuticals,2024-08-01,1.0,0.0,1

In [ ]:
logistics_data['Number of Shipments'].unique()

array([ 1,  2,  5,  4,  3,  8,  9,  6, 13, 10,  7, 19, 12, 15, 14, 22, 25,
       16, 11, 32, 23, 17, 18])

In [ ]:
duplicate_rows = logistics_data.duplicated()
duplicate_rows.sum()

np.int64(23512)

In [ ]:
logistics_data[logistics_data.duplicated()]

,Country,Transportation Mode,Product Category,Agreed Delivery Date Year Month,On Time (OTD),Average Days Late,Number of Shipments
10,Congo DRC,Land,Laboratory Reagents,2017-04-01,1.0,0.0,1
16,Mozambique,Land,Others,2017-08-01,1.0,-5.0,1
24,Congo DRC,Land,Laboratory Consumables,2017-04-01,1.0,-4.0,1
31,Congo DRC,Land,Laboratory Reagents,2017-04-01,1.0,-4.0,1
32,Congo DRC,Land,Laboratory Reagents,2017-04-01,1.0,-4.0,1
...,...,...,...,...,...,...,...
43390,Benin,Sea,Long Lasting Insecticide Treated Nets (LLINs),2020-02-01,1.0,0.0,1
43392,Burkina Faso,Sea,Long Lasting Insecticide Treated Nets (LLINs),2019-06-01,1.0,0.0,1
43393,Malawi,Sea,Malaria Rapid Diagnostic Test (RDTs),2019-12-01,1.0,0.0,1
43394,Kenya,Sea,Long Lasting Insecticide Treated Nets (LLINs),2023-12-01,1.0,0.0,1
43395,Congo DRC,Sea,Malaria Pharmaceuticals,2024-08-01,1.0,0.0,1

In [ ]:
logistics_data = logistics_data.drop_duplicates()
logistics_data

,Country,Transportation Mode,Product Category,Agreed Delivery Date Year Month,On Time (OTD),Average Days Late,Number of Shipments
0,Haiti,Land,Laboratory Reagents,2017-02-01,1.0,5.0,1
1,Zambia,Land,Laboratory Reagents,2018-07-01,1.0,1.0,1
2,Mozambique,Land,Laboratory Reagents,2017-05-01,1.0,0.0,1
3,Zambia,Land,Laboratory Reagents,2019-12-01,1.0,4.0,1
4,Mozambique,Land,Laboratory Equipment,2017-12-01,1.0,-7.0,1
...,...,...,...,...,...,...,...
43381,Zimbabwe,Air,Malaria Pharmaceuticals,2020-02-01,1.0,0.0,1
43382,Rwanda,Sea,Malaria Pharmaceuticals,2020-07-01,1.0,0.0,1
43384,Liberia,Sea,Long Lasting Insecticide Treated Nets (LLINs),2022-06-01,1.0,0.0,1
43386,Zambia,Air,Laboratory Equipment,2018-05-01,1.0,0.0,1
43391,Liberia,Sea,Malaria Pharmaceuticals,2021-07-01,1.0,0.0,1

In [ ]:
logistics_data["On Time (OTD)"].isnull().sum()

np.int64(0)

In [ ]:
logistics_data.to_csv("USAID_logistics_data.csv", index=False)